In [10]:
import finesse

In [ ]:
# Simulating michelson interferometer using Finesse 3

import finesse
import finesse
from finesse import Model
import matplotlib.pyplot as plt

# Create model
model = Model()

model.parse(
"""
l L0 P=1     # Laser with power 1 W
s s0 L0.p1 bs.p1 L=1     # Input space to beamsplitter
bs bs R=0.5 T=0.5 alpha=45     # Beamsplitter with 50/50 split and 45 degree angle

s sx bs.p2 mx.p1 L=100     # X arm
m mx R=1 T=0

s sy bs.p3 my.p1 L=100     # Y arm
m my R=1 T=0

pd dark bs.p4     # Dark port photodetector
"""
)

# Plotting power detected at photodiode as a function of differential arm length
differential_lengths = [i * 0.01 for i in range(-100, 101)]  # Differential lengths from -1 m to 1 m
detected_powers = []

<ArraySolution of noxaxis @ 0x24109f27c60 children=0>

In [21]:
import finesse
from finesse import Model
import matplotlib.pyplot as plt
import numpy as np
from finesse.analysis.actions import Xaxis


kat = Model()

kat.parse("""
# Laser
l laser P=1

# Input path
s s0 laser.p1 bs.p1 L=1

# Beam splitter (50:50)
bs bs R=0.5 T=0.5 alpha=45

# X arm
s sx bs.p2 mx.p1 L=10
m mx R=1 T=0

# Y arm
s sy bs.p3 my.p1 L=10
m my R=1 T=0

# Power detector at antisymmetric port
pd AS bs.p4
""")

out = kat.run(
    Xaxis(
        parameter="sx.L",
        mode="lin",
        start=10-5e-7,
        stop=10+5e-7,
        steps=1000,
    )
)

# Plotting the results
plt.plot(out.x, out["AS"])
plt.xlabel("X-arm length (m)")
plt.ylabel("Power at AS port (W)")
plt.grid(True)
plt.show()

c:\Users\ABC\miniconda3\Lib\site-packages\finesse\detectors\general.py:56: UserWarning: Detector node not specified. Assuming 'bs.p4.i'.
  warn(


ImportError: cannot import name 'backend_agg' from 'matplotlib.backends' (c:\Users\ABC\miniconda3\Lib\site-packages\matplotlib\backends\__init__.py)

In [22]:
print(out)
print(out["AS"])
print(out.x)

- Solution Tree
● xaxis - ArraySolution
[0. 0. 0. ... 0. 0. 0.]
(array([ 9.9999995,  9.9999995,  9.9999995, ..., 10.0000005, 10.0000005,
       10.0000005], shape=(1001,)),)


In [19]:
print(out.x)
print(type(out.x))

(array([ 9.9999995,  9.9999995,  9.9999995, ..., 10.0000005, 10.0000005,
       10.0000005], shape=(1001,)),)
<class 'tuple'>


In [6]:
print(finesse.__version__)

3.0b2


In [13]:
from finesse import Model
import matplotlib.pyplot as plt

kat = Model()

kat.parse("""
l laser P=1

s s0 laser.p1 bs.p1 L=1

bs bs R=0.5 T=0.5 alpha=45

s sx bs.p2 mx.p1 L=10
m mx R=1 T=0

s sy bs.p3 my.p1 L=10
m my R=1 T=0

pd AS bs.p4

xaxis(sx.L, lin, -1u, 1u, 1000)
""")

out = kat.run()

plt.plot(out.x, out["AS"])
plt.xlabel("Differential arm length (m)")
plt.ylabel("Power at AS port")
plt.grid()
plt.show()

c:\Users\ABC\miniconda3\Lib\site-packages\finesse\detectors\general.py:56: UserWarning: Detector node not specified. Assuming 'bs.p4.i'.
  warn(


ValueError: Length of a space must not be negative.

In [8]:
import finesse.examples as ex
print(dir(ex))

ModuleNotFoundError: No module named 'finesse.examples'

In [9]:
from finesse import Model

kat = Model()

print(dir(kat))

['ABCD', 'Nhoms', '_Model__add_connection_to_graph', '_Model__add_node_to_graph', '_Model__analysis', '_Model__cavities', '_Model__components', '_Model__default_sim_trace_config', '_Model__detectors', '_Model__dofs', '_Model__elements', '_Model__freq_map', '_Model__frequencies', '_Model__frequency_change_callbacks', '_Model__gausses', '_Model__inmtx_dc', '_Model__insert_trace_dependency', '_Model__is_built', '_Model__last_trace', '_Model__lock_model_change', '_Model__locks', '_Model__make_trace_order_override', '_Model__mode_setting', '_Model__model_parameters', '_Model__network', '_Model__node_exists_check', '_Model__nodes_of', '_Model__not_removable', '_Model__opt_net_view', '_Model__optical_node_from_str', '_Model__parse_path_nodes', '_Model__pre_build_checks', '_Model__sim_trace_config', '_Model__toggle_param_locks', '_Model__trace_forest', '_Model__trace_order', '____FROZEN____', '__class__', '__deepcopy__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__firstlineno

In [ ]:
C:\Users\ABC>conda create -n finesse
'conda' is not recognized as an internal or external command,
operable program or batch file.

In [24]:
import ssl
print(ssl)

<module 'ssl' from 'c:\\Users\\ABC\\miniconda3\\Lib\\ssl.py'>


In [25]:
import sys
print(sys.executable)

c:\Users\ABC\miniconda3\python.exe
